### PR TITLE
Fixed the issue#45

### LINKED ISSUE #45: Database does not exist
When I run `rails db:create` || `bundle exec rails db:create` I get the stack trace given below.
```bash
~/apps/project/myapp$ bin/rails db:create
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "myapp_development" does not exist
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `rescue in connect'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:680:in `connect'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/connection_handling.rb:90:in `connection'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/bundler/gems/rails-6d1dd1643dc8/activerecord/lib/active_record/model_schema.rb:324:in `table_exists?'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/gems/gutentag-2.0.0/lib/gutentag/tag_validations.rb:26:in `add_length_validation?'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/gems/gutentag-2.0.0/lib/gutentag/tag_validations.rb:34:in `validation_options'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/gems/gutentag-2.0.0/lib/gutentag/tag_validations.rb:18:in `call'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/gems/gutentag-2.0.0/lib/gutentag/tag_validations.rb:10:in `call'
/home/developer/.rvm/gems/ruby-2.4.1@myapp/gems/gutentag-2.0.0/lib/gutentag.rb:46:in `block in <top (required)>'
```
It is not allowing me to create a database.

### PR DESCRIPTION
**Pull request by om-nishu-trantor**
This fixes #45

### CODE REVIEW

**Comment by om-nishu-trantor** [comment]
@pat Please have a look at this.

**Comment by pat** [comment]
@om-nishu-trantor thanks for the patch! It looks pretty good - but you don't need the `begin` and `end` calls - do you want to push a new commit that simplifies it? The following should do the trick:

```ruby
def add_length_validation?
  klass.table_exists? && limit.present?
rescue ActiveRecord::NoDatabaseError
  false
end
```

This should also get you past the Rubocop failures in the build.

**Comment by pat** [comment]
Thank you! :)

**Comment by pat** [comment]
Just released v2.1.0 which includes this patch :)

**Comment by om-nishu-trantor** [comment]
:+1:

**Pull request merged**
