### PR TITLE
test rails 5.1

### PR DESCRIPTION
**Pull request by grosser**
@pat

### CODE REVIEW

**Comment by pat** [comment]
Generally a fan of this PR, though I have a few thoughts:

I think I'd rather not have an upper limit on the version constraint for ActiveRecord… sometimes newer versions work well, sometimes they don't, but I think I'd rather presume the former as much as possible, rather than potentially requiring _just_ that constraint be changed for supporting future versions.

Having the logic repeated for the right migration superclass in each migration file is a bit ugly… my initial thought was to move that logic into `lib/gutentag.rb`, assign the result to `Gutentag::Migration` or similar, and then use that in each file instead. But I guess Rails just copies the files over, which means Gutentag then becomes a requirement for an app's migrations, and that isn't so cool.

I did try to delve into the migration/engine code in Rails a while ago to see if there was a better way forward here, but I didn't find one. Certainly, the migration changes in Rails make it pretty annoying to support multiple Rails versions in engines (though I see their value generally!). At some point I'd like to puzzle through what the Right Way to handle this in a cross-version manner would be - if such a thing is possible. Guess it's another thing to keep pondering for the moment…

**Comment by grosser** [comment]
can always merge and then improve :)

**Comment by pat** [comment]
Yeah, I think that's the right place to start - though would you be able to remove the version constraint change (and then squash it back down to a single commit) first, please?

**Comment by grosser** [comment]
removed the constraint

**Comment by pat** [comment]
Thanks :)

**Pull request merged**
