### PR TITLE
added explicit setter in tag model, removed callback

### PR DESCRIPTION
**Pull request by RasMachineMan**
1. Removed before_validation callback
2. Added explicit setter for name

### CODE REVIEW

**Comment by pat** [comment]
Thanks Tomasz, appreciate the patch, but I'm curious as to why? What's prompted these changes?

**Comment by pboling** [comment]
One benefit may be that this will work even when callbacks are skipped.

**Comment by apneadiving** [comment]
I would say using setter makes the intent clear and the less callbacks the better.

**Comment by RasMachineMan** [comment]
Yeah, I would stay away from callbacks as much as possible. Also, as @apneadiving commented, setters express intention more clearly.

**Comment by pat** [comment]
Fair enough. I agree that callbacks should be avoided where possible - though I'm less concerned when they're used to address internal model behaviour (as opposed to involving other models, or worse still external APIs, etc).

The trade-off here is that the normalisation will _only_ occur when the name is set via the setter. Thankfully ActiveRecord uses setters via `.new`, `.create`, `#update_attributes` and `#update_attribute`, so the trade-off is worth it.

As for callbacks being skipped - sadly ActiveRecord does not use the setter for `#update_column` or `#update_columns`, so it'll only be more reliable in the case of using `#save` with `:validate => false`.

**Comment by pat** [comment]
Thanks Tomasz for the PR, and everyone for their thoughts on the change 👍

**Comment by RasMachineMan** [comment]
Sure thing. Cool project btw.

**Comment by pboling** [comment]
```
As for callbacks being skipped - sadly ActiveRecord does not use the setter for #update_column or #update_columns, so it'll only be more reliable in the case of using #save with :validate => false.
```

In the case of `update_column[s]` the callbacks have always been skipped, so the name normalizer has never worked there to begin with, and this change continues that pattern, so no gain, no loss.

**Pull request merged**
