### PR TITLE
enforce test coverage

### PR DESCRIPTION
**Pull request by grosser**
screen shot 2017-05-04 at 9 29 07 pm
(screenshot from introducing a new untested bogus method)

a cheap/simple/helpful way to check if all the newly added logic is actually covered ... fails and shows what is missing covereage

### CODE REVIEW

**Comment by pat** [comment]
Certainly appreciate this patch, and I've merged it in, but I'm noticing occasional crashes of Ruby, both locally, and on [Travis](https://travis-ci.org/pat/gutentag/jobs/229895494). Previously, this hadn't been an issue, so I'm wondering if it's related to something SimpleCov is doing?

**Comment by pat** [comment]
SingleCov, rather.

**Comment by grosser** [comment]
I've seen a few on pre 2.3.3 ... after that was never able to replicate, so
could deactivate on lower versions if you see them again ... coverage
should still be accurate.

**Comment by pat** [comment]
I'm still seeing occasional failures on 2.4.1 on my machine, and here's one from Travis: https://travis-ci.org/pat/gutentag/jobs/232660243#L323

**Comment by grosser** [comment]
... the library is just using ruby ... so idk how to fix that ... if you
find a way to reproduce we can open a ruby issue ... or we rescue the
segfault ;)

**Pull request merged**
