### PR TITLE
class/module name must be CONSTANT

### PR DESCRIPTION
**Pull request by lucasmpereira**
just a minor typo class/module name must be CONSTANT

### CODE REVIEW

**Comment by pboling** [comment]
A constant, like a class, assigned to a local variable, is still a constant.

I don't think this change is required, though it may read better for some people.  In Ruby meta programming working with constants as local variables is quite common.

Perhaps more importantly, if you define a constant without any containing scope in a Ruby script, then the constant is defined as part of Object.

```
∴ ruby const.rb
As a constant defined on Object the reference to CONSTANT will never be garbage collected so long as the Ruby process continues: Integer
However, a local variable will be garbade collected when the scope (the file) is done being lexically read into the Ruby process: Integer
```
Here is what the script looks like:
```
∴ cat const.rb
CONSTANT = Integer

puts "As a constant defined on Object the reference to CONSTANT will never be garbage collected so long as the Ruby process continues: " + Object::CONSTANT.to_s

local = Integer

puts "However, a local variable will be garbade collected when the scope (the file) is done being lexically read into the Ruby process: " + local.to_s
```

**Comment by lucasmpereira** [comment]
Hmmm, okay, I understantd your explanation. 

I make this PR just because thought that would be more readable to peoples and in convetion but maybe it's not something really needed. 

Thanks anyway for the feedback

**Comment by pat** [comment]
@lucasmpereira certainly, the PR is appreciated :)

I'm going to keep the code as it is, because while yes I certainly understand that normally for such usage a constant would make sense, I'm really only expecting this variable to be present for the current file/context, rather than available globally. This is particularly the case given it's the same approach in each of the migration files (otherwise, it might make slightly more sense to define it once and use it in all three).

To be honest, I'm not thrilled at all with my approach here, but I can't think of a better way to allow for the gem to be used with projects prior to Rails v5.

**Comment by pat** [comment]
But yes, beside all of my thinking, I'm still happy you made the effort!

**Pull request closed without merging**
