### PR TITLE
silence

### PR DESCRIPTION
**Pull request by grosser**
@pat

current test run is pretty noisy ... prefer silence to see when something is actually broken

### CODE REVIEW

**Comment by pat** [comment]
Definitely keen to get this merged in, but looks like the tests are all failing :( Any chance you can fix it? Or if you need me to look into it, I should be able to find some time soon.

**Comment by grosser** [comment]
fixed

**Comment by grosser** [comment]
fixed

**Comment by pat** [comment]
Merged this in, and then pulled the silencing of migrations/schema import over to Combustion instead :) Thanks!

**Pull request merged**
